name: rai_fanancil_services
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # State Management
  get: ^4.6.6

  # UI & Fonts
  google_fonts: ^6.2.1
  flutter_spinkit: ^5.2.1
  flutter_easyloading: ^3.0.5
  jwt_decoder: ^2.0.1
  # Images
  cached_network_image: ^3.4.1
  image_picker: ^1.1.2
  file_picker: ^8.1.2

  # Utilities
  logger: ^2.5.0
  intl: ^0.20.2
  shared_preferences: ^2.3.2

  # Network
  http: ^1.2.2

  # Maps
  google_maps_flutter: ^2.9.0

  # Input
  intl_phone_number_input: ^0.7.4

  # Tools
  change_app_package_name: ^1.5.0
  rename: ^3.0.2
  fl_chart: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

  flutter_launcher_icons: ^0.14.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/logos/

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logos/Primary-Logo 1.png"
